[package]
name = "reservation"
version = "0.1.0"
edition = "2021"
license = "Unicode-DFS-2016"
[dependencies]
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
